# permissions for end users to edit logforwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: logforwarder-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multi-cluster-operator-new
    app.kubernetes.io/part-of: multi-cluster-operator-new
    app.kubernetes.io/managed-by: kustomize
  name: logforwarder-editor-role
rules:
- apiGroups:
  - multicluster.samanthajayasinghe.github.io
  resources:
  - logforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.samanthajayasinghe.github.io
  resources:
  - logforwarders/status
  verbs:
  - get
