---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - multicluster.samanthajayasinghe.github.io
  resources:
  - logforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.samanthajayasinghe.github.io
  resources:
  - logforwarders/finalizers
  verbs:
  - update
- apiGroups:
  - multicluster.samanthajayasinghe.github.io
  resources:
  - logforwarders/status
  verbs:
  - get
  - patch
  - update
